### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by hokascha** [Garefild/PoeditSmarty#11]
I downloaded the jar file, executed it, this is what happens:

```
$ java -jar PoeditSmarty.jar -h
java.nio.file.NoSuchFileException: /tmpSmarty/log/14072021165453.txt.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:478)
	at java.util.logging.FileHandler.<init>(FileHandler.java:310)
	at core.Logger.createLogFile(Logger.java:246)
	at core.Logger.<init>(Logger.java:67)
	at PoeditSmarty.<clinit>(PoeditSmarty.java:28)



/**
 * ______              _ _ _   _____                      _         
 * | ___ \            | (_) | /  ___|                    | |        
 * | |_/ /__   ___  __| |_| |_\ `--. _ __ ___   __ _ _ __| |_ _   _ 
 * |  __/ _ \ / _ \/ _` | | __|`--. \ '_ ` _ \ / _` | '__| __| | | |
 * | | | (_) |  __/ (_| | | |_/\__/ / | | | | | (_| | |  | |_| |_| |
 * \_|  \___/ \___|\__,_|_|\__\____/|_| |_| |_|\__,_|_|   \__|\__, |
 *  https://github.com/Garefild/PoeditSmarty                   __/ |
 *                                                            |___/ 
 * @Author Garefild
 * @Copyright 2010-2035
 * @version 3.0.0 
 */

[info] [-h]
Exception in thread "main" java.lang.NullPointerException
	at core.Logger.info(Logger.java:133)
	at arguments.RenderArguments.parse(RenderArguments.java:140)
	at PoeditSmarty.main(PoeditSmarty.java:48)
```

Looks like the /tmp path has no trailing slash. This is on Ubuntu Linux.

**Comment by hokascha** [comment]
Add `-Djava.io.tmpdir=/tmp/` to your command to set the temp dir path, so my complete command in Poedit looks like this:
`‪/usr/bin/java  -Djava.io.tmpdir=/tmp/ -jar PoeditSmarty.jar -o %o -c %C -k %K -f %F`
