### ISSUE TITLE
Error with 3.0.0 while scanning the template files

### ISSUE THREAD

**Issue by spfmoby** [Garefild/PoeditSmarty#15]
Windows 11
JDK 1.8
POEdit 3.4.2

Error :
18/01/2024 20:02:35: Translation entries in the file are probably incorrect.
18/01/2024 20:02:35: Updating the file failed. Click on 'Details >>' for details.
18/01/2024 20:02:34: Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal repetition near index 11
18/01/2024 20:02:34: (?<=\{)(\s*){_(\s*)\((?:"|')(.+?)(?:"|')\)(\s*)(?=\})|(?<=\{)(\s*)(?:"|')(.+?)("|')(\s*)\|(\s*){_(\s*)\}
	^
	at java.util.regex.Pattern.error(Pattern.java:1969)
	at java.util.regex.Pattern.closure(Pattern.java:3171)
	at java.util.regex.Pattern.group0(Pattern.java:2926)
	at java.util.regex.Pattern.sequence(Pattern.java:2065)
	at java.util.regex.Pattern.expr(Pattern.java:2010)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1352)
	at java.util.regex.Pattern.compile(Pattern.java:1054)
	at parse.ParseData.renderPatternKeywords(ParseData.java:119)
	at PoeditSmarty.main(PoeditSmarty.java:57)

Some translations are properly detected, but I'm not sure that all files are properly scanned.

**Comment by spfmoby** [comment]
Same error with 3.1.1:

19/01/2024 13:37:12: Translation entries in the file are probably incorrect.
19/01/2024 13:37:12: Updating the file failed. Click on 'Details >>' for details.
19/01/2024 13:37:11: Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal repetition near index 11
19/01/2024 13:37:11: (?<=\{)(\s*){_(\s*)\((?:"|')(.+?)(?:"|')\)(\s*)(?=\})|(?<=\{)(\s*)(?:"|')(.+?)("|')(\s*)\|(\s*){_(\s*)\}
	^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2027)
	at java.base/java.util.regex.Pattern.closure(Pattern.java:3320)
	at java.base/java.util.regex.Pattern.group0(Pattern.java:3064)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2123)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2068)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1782)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1428)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1094)
	at parse.ParseData.renderPatternKeywords(ParseData.java:119)
	at PoeditSmarty.main(PoeditSmarty.java:57)

**Comment by spfmoby** [comment]
The problem was coming from a malformed custom "source keyword" added by mistake. Problem solved
